server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/expressage?useUnicode=true
        username: root
        password: 110412
    #邮箱配置
    mail:
        host: smtp.163.com
        username: 18216308307@163.com
        #QQ邮箱的授权码
        password: m4gewo
        default-encoding: UTF-8
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
    thymeleaf:
        mode: HTML
        encoding: UTF-8
        servlet:
            content-type: text/html
        cache: false
        suffix: .html
        prefix: classpath:/templates/


#设置一个邮件发送人
want:
    mail:
        senderName: want-conpany


mybatis:
    mapper-locations:
        - classpath:mapper/*.xml
        - classpath*:com/**/mapper/*.xml

# 自定义jwt key
#jwt:
#    tokenHeader: Authorization #JWT存储的请求头
#    secret: mySecret #JWT加解密使用的密钥
#    expiration: 604800 #JWT的超期限时间(60*60*24)


#    如果要编写除控制台输出之外的日志文件，则需在application.properties中设置logging.file或logging.path属性。
#
#    logging.file，设置文件，可以是绝对路径，也可以是相对路径。如：logging.file=my.log
#    logging.path，设置目录，会在该目录下创建spring.log文件，并写入日志内容，如：logging.path=/var/log
#    如果只配置 logging.file，会在项目的当前路径下生成一个 xxx.log 日志文件。
#    如果只配置 logging.path，在 /var/log文件夹生成一个日志文件为 spring.log
#    ————————————————
#    版权声明：本文为CSDN博主「Inke」的原创文章，遵循 CC 4.0 BY-SA 版权协议，转载请附上原文出处链接及本声明。
#    原文链接：https://blog.csdn.net/Inke88/article/details/75007649
logging:
    file:
        path: /logs
    level:
        com.example.express_dena: DEBUG
        com.example.express_dena.controller: info
        com.example.express_dena.services: warn
        com.example.express_dena.mapper: error
    pattern:
        file: "%d{yyyy-MM-dd} --- %-5level --- [%thread] --- %logger{50} --- %msg%n"





#    tokenHead: Bearer  #JWT负载中拿到开头